import streamlit as st
import pandas as pd
from PIL import Image
import os

# Import the recommendation engine logic
from src.recommender.recommend import recommend_outfit

# Load cleaned tags generated by Teammates A & B
@st.cache_data
def load_data():
    return pd.read_csv("data/cleaned_tags.csv")

df = load_data()

st.title("AI Closet – Outfit Recommendation System")

# Sidebar for filters
st.sidebar.header("Filters")
weather = st.sidebar.selectbox("Weather:", ["Any", "Hot", "Cold", "Mild"])
occasion = st.sidebar.selectbox("Occasion:", ["Any", "Casual", "Formal", "Sport"])

# Main UI
st.subheader("Your Wardrobe Items")

# Display list of clothing to choose from
item = st.selectbox("Choose an item you want to style:", df["item_name"].unique())

# Show selected item image
image_path = df.loc[df["item_name"] == item, "image_path"].values[0]
if os.path.exists(image_path):
    st.image(Image.open(image_path), width=250)

# Generate recommendations
if st.button("Recommend Outfit"):
    with st.spinner("Thinking..."):
        recommendations = recommend_outfit(df, item, weather, occasion)

    st.subheader("Suggested Outfit:")
    for rec in recommendations:
        st.write(f"• **{rec['item_name']}** ({rec['category']})")

        # Show images if available
        if os.path.exists(rec["image_path"]):
            st.image(Image.open(rec["image_path"]), width=200)
